services:
  ladica-sync-backend:
    container_name: ladica-sync-backend
    image: ghcr.io/karlohrvacic/linker-be:main
    restart: unless-stopped
    ports:
      - "8086:8080"
    networks:
      - ladica-internal-data
      - nginx-proxy_default
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_BASE64_SECRET: ${JWT_BASE64_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      OAUTH2_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

  ladica-postgres:
    image: postgres:18-alpine
    container_name: ladica-postgres
    restart: always
    environment:
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: mVQCHb0HSYMDf9VE4bXfWKbnJYmh4TlM
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    networks:
      - ladica-internal-data
    volumes:
      - ladica_postgres_data:/var/lib/postgresql

volumes:
  ladica_postgres_data:

networks:
  nginx-proxy_default:
    external: true
  ladica-internal-data:
    driver: bridge
